# This workflow will do a clean install of node dependencies, build the source code for every push and pull requests

name: Lint & Build

on:
  - push
  - pull_request
  - workflow_dispatch

jobs:
  createCRA:
    runs-on: ubuntu-latest
    steps:
      - name: â¬‡ï¸ Checkout repo
        uses: actions/checkout@v3
      - name: Use Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Create CRA from template
        run: npx create-react-app my-app --template file:../cra-template-quentinvdr .
      - run: ls -a
        working-directory: ./my-app
      - run: cat package.json
        working-directory: ./my-app
      - name: ğŸ“¦ Install Dependencies
        run: npm install
        working-directory: ./my-app
      - name: ğŸ¨ Eslint
        run: npm run lint
        working-directory: ./my-app
      - name: ğŸ“¦ Build
        run: npm run build
        working-directory: ./my-app
      - name: ğŸ¨ Eslint
        run: npm run lint
        working-directory: ./my-app
