# This workflow will do a clean install of node dependencies, build the source code for every push and pull requests

name: Lint & Build

on:
  - push
  - pull_request
  - workflow_dispatch

jobs:
  createCRAAndLintBuild:
    runs-on: ubuntu-latest
    steps:
      - name: â¬‡ï¸ Checkout repo
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - name: Use Node.js 20
        uses: actions/setup-node@8f152de45cc393bb48ce5d89d36b731f54556e65 # v4
        with:
          node-version: 20
      - name: Create CRA from template
        run: npx create-react-app my-app --template file:../cra-template-quentinvdr .
      - name: ğŸ“¦ Install Dependencies
        run: npm install
        working-directory: ./my-app
      - name: ğŸ¨ Eslint
        run: npm run lint
        working-directory: ./my-app
      - name: ğŸ“¦ Build
        run: npm run build
        working-directory: ./my-app
